development:
  sessions:
    default:
      database: cloud_storage_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: cloud_storage_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
